version: 2
updates:
  - package-ecosystem: github-actions
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: daily
      timezone: Asia/Jakarta
    open-pull-requests-limit: 1

  - package-ecosystem: gradle
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: daily
      timezone: Asia/Jakarta
