name: Xray-core lib

on:
  workflow_dispatch:
    branches:
      - dev
    inputs:
      CORE:
        description: 'versi of the Xray-core'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.5'
        cache: false

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Build dependencies
      run: |
        cd ${{ github.workspace }}/AndroidLibXrayLite
        mkdir -p assets data
        bash gen_assets.sh download
        mv -v data/*.dat assets/
        go get github.com/xtls/xray-core@${{ github.event.inputs.CORE }} || true
        gomobile init
        go mod tidy -v
        gomobile bind -v -androidapi 27 -ldflags='-s -w' ./
        mv *.aar ${{ github.workspace }}/app/libs/

    - name: Update library
      run: |
        git config --global user.email jarbull86@gmail.com
        git config --global user.name AnGgIt86
        rm -rfd ${{ github.workspace }}/AndroidLibXrayLite/*.jar
        git add -f .
        git commit -m "Core Update ${{ github.event.inputs.CORE }}"
        git push
