name: Build and Test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare build dir
      run: |
        mkdir ${{ github.workspace }}/build

    - name: Fetch AndroidLibV2rayLite
      run: |
        cd ${{ github.workspace }}/build
        git clone --depth=1 -b master https://github.com/2dust/AndroidLibV2rayLite.git
        cd AndroidLibV2rayLite
        git submodule update --init

    - name: Restore cached libtun2socks
      id: cache-libtun2socks-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/build/AndroidLibV2rayLite/libs
        key: libtun2socks-${{ runner.os }}-${{ hashFiles('build/AndroidLibV2rayLite/.git/refs/heads/master') }}-${{ hashFiles('build/AndroidLibV2rayLite/.git/modules/badvpn/HEAD') }}-${{ hashFiles('build/AndroidLibV2rayLite/.git/modules/libancillary/HEAD') }}

    - name: Setup Android NDK
      if: steps.cache-libtun2socks-restore.outputs.cache-hit != 'true'
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      # Same version as https://gitlab.com/fdroid/fdroiddata/metadata/com.v2ray.ang.yml
      with:
        ndk-version: r27
        add-to-path: true
        link-to-sdk: true
        local-cache: true

    - name: Restore Android Symlinks
      if: steps.cache-libtun2socks-restore.outputs.cache-hit != 'true'
      run: |
        directory="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin"
        find "$directory" -type l | while read link; do
            current_target=$(readlink "$link")
            new_target="$directory/$(basename "$current_target")"
            ln -sf "$new_target" "$link"
            echo "Changed $(basename "$link") from $current_target to $new_target"
        done

    - name: Build libtun2socks
      if: steps.cache-libtun2socks-restore.outputs.cache-hit != 'true'
      run: |
        cd ${{ github.workspace }}/build/AndroidLibV2rayLite
        bash compile-tun2socks.sh
        tar -xvzf libtun2socks.so.tgz
        cp -r libs/* ${{ github.workspace }}/V2rayNG/app/libs/
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Save libtun2socks
      if: steps.cache-libtun2socks-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/build/AndroidLibV2rayLite/libs
        key: libtun2socks-${{ runner.os }}-${{ hashFiles('build/AndroidLibV2rayLite/.git/refs/heads/master') }}-${{ hashFiles('build/AndroidLibV2rayLite/.git/modules/badvpn/HEAD') }}-${{ hashFiles('build/AndroidLibV2rayLite/.git/modules/libancillary/HEAD') }}

    - name: Copy libtun2socks
      run: |
        cp -r ${{ github.workspace }}/build/AndroidLibV2rayLite/libs/* ${{ github.workspace }}/V2rayNG/app/libs/

    - name: Download libv2ray
      uses: robinraju/release-downloader@v1
      with:
        repository: '2dust/AndroidLibXrayLite'
        latest: true
        fileName: 'libv2ray.aar'
        out-file-path: V2rayNG/app/libs/

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android environment
      uses: android-actions/setup-android@v3

    - name: Build
      run: |
        cd ${{ github.workspace }}/V2rayNG
        chmod 755 gradlew
        ./gradlew assemble

    - name: arm64
      uses: actions/upload-artifact@v4
      if: ${{  success() }}
      with:
        name: Arm64
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/release/*arm64-v8a.apk

    - name: armeabi-v7a
      uses: actions/upload-artifact@v4
      if: ${{  success() }}
      with:
        name: Armeabi-v7a
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/release/*armeabi-v7a.apk

    - name: x86
      uses: actions/upload-artifact@v4
      if: ${{  success() }}
      with:
        name: X86
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/release/*x86.apk

    - name: x86_64
      uses: actions/upload-artifact@v4
      if: ${{  success() }}
      with:
        name: X86_64
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/release/*x86_64.apk

    - name: universal
      uses: actions/upload-artifact@v4
      if: ${{  success() }}
      with:
        name: Universal
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/release/*universal.apk

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      if: github.event.inputs.release_tag != ''
      with:
        file: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*playstore*/release/*.apk
        tag: ${{ github.event.inputs.release_tag }}
        file_glob: true
        prerelease: true
