name: Update Gradle wrapper

on:
  schedule: [{cron: "0 17 * * *"}]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build dependencies
      run: |
        ./gradlew wrapper --gradle-version latest --distribution-type bin

    - name: Update library
      run: |
        git config --global user.email jarbull86@gmail.com
        git config --global user.name AnGgIt86
        git add -f .
        git commit -m "Update gradle wrapper in latest version"
        git push
